package com.androidlab.zhihudaily.data.local;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.androidlab.zhihudaily.data.bean.Collection;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "Collection".
 */
public class CollectionDao extends AbstractDao<Collection, Long> {

    public static final String TABLENAME = "Collection";

    /**
     * Properties of entity Collection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Time = new Property(1, String.class, "time", false, "time");
        public final static Property NoteText = new Property(2, String.class, "noteText", false, "noteText");
        public final static Property Picture = new Property(3, String.class, "picture", false, "picture");
        public final static Property Url = new Property(4, String.class, "url", false, "url");
    }


    public CollectionDao(DaoConfig config) {
        super(config);
    }

    public CollectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"Collection\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"time\" TEXT," + // 1: time
                "\"noteText\" TEXT," + // 2: noteText
                "\"picture\" TEXT," + // 3: picture
                "\"url\" TEXT);"); // 4: url
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Collection\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Collection entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }

        String noteText = entity.getNoteText();
        if (noteText != null) {
            stmt.bindString(3, noteText);
        }

        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(4, picture);
        }

        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Collection entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }

        String noteText = entity.getNoteText();
        if (noteText != null) {
            stmt.bindString(3, noteText);
        }

        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(4, picture);
        }

        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Collection readEntity(Cursor cursor, int offset) {
        Collection entity = new Collection( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // time
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // noteText
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // picture
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // url
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Collection entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNoteText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPicture(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
    }

    @Override
    protected final Long updateKeyAfterInsert(Collection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Collection entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Collection entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
